# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulates species tree using constant rate birth-death process
#'
#' @description Forward simulates to a number of tips. This function does so using
#'     the general algorithm of Hartmann et al. 2010.
#' @param sbr species birth rate (i.e. speciation rate)
#' @param sdr species death rate (i.e. extinction rate)
#' @param numbsim number of species trees to simulate
#' @param n_tips number of tips to simulate to
#' @param gsa_stop_mult number of tips to simulate the GSA tip to
#' @return List of objects of the tree class (as implemented in APE)
#' @references
#' K. Hartmann, D. Wong, T. Stadler. Sampling trees from evolutionary models.
#'     Syst. Biol., 59(4): 465-476, 2010.
#'
#' T. Stadler. Simulating trees on a fixed number of extant species.
#'     Syst. Biol., 60: 676-684, 2011.
#' @examples
#' mu <- 0.5 # death rate
#' lambda <- 2.0 # birth rate
#' numb_replicates <- 10
#' numb_extant_tips <- 4
#' # simulate trees under the GSA so first simulates a tree with
#' # numb_extant_tips * 100 tips counting each time we have a tree with 10 tips
#' # then randomly picks one of those trees
#'
#' tree_list <- sim_sptree_bdp(sbr = lambda,
#'                 sdr = mu,
#'                 numbsim = numb_replicates,
#'                 n_tips = numb_extant_tips)
sim_sptree_bdp <- function(sbr, sdr, numbsim, n_tips, gsa_stop_mult = 10L) {
    .Call(`_treeducken_sim_sptree_bdp`, sbr, sdr, numbsim, n_tips, gsa_stop_mult)
}

#' Simulates species tree using constant rate birth-death process to a time
#'
#' @description Forward simulates a tree until a provided time is reached.
#' @param sbr species birth rate (i.e. speciation rate)
#' @param sdr species death rate (i.e. extinction rate)
#' @param numbsim number of species trees to simulate
#' @param t time to simulate to
#' @return List of objects of the tree class (as implemented in APE)
#' @references
#' K. Hartmann, D. Wong, T. Stadler. Sampling trees from evolutionary models.
#'     Syst. Biol., 59(4): 465-476, 2010.
#'
#' T. Stadler. Simulating trees on a fixed number of extant species.
#'     Syst. Biol., 60: 676-684, 2011.
#' @examples
#' mu <- 0.5 # death rate
#' lambda <- 2.0 # birth rate
#' numb_replicates <- 10
#' time <- 2
#'
#' tree_list <- sim_sptree_bdp_time(sbr = lambda,
#'                 sdr = mu,
#'                 numbsim = numb_replicates,
#'                 t = time)
sim_sptree_bdp_time <- function(sbr, sdr, numbsim, t) {
    .Call(`_treeducken_sim_sptree_bdp_time`, sbr, sdr, numbsim, t)
}

#' Simulates locus tree using constant rate birth-death-transfer process
#'
#' @description Given a species tree simulates a locus or gene family tree along
#'     the species tree.
#' @param species_tree species tree to simulate along
#' @param gbr gene birth rate
#' @param gdr gene death rate
#' @param lgtr gene trasnfer rate
#' @param num_loci number of locus trees to simulate
#' @param transfer_type The type of transfer input. Acceptable options: "cladewise" or "random"
#' @return List of objects of the tree class (as implemented in APE)
#' @details Given a species tree will perform a birth-death process coupled with transfer.
#' The simulation runs along the species tree speciating and going extinct in addition to locus tree birth and deaths.
#' Thus with parameters set to 0.0 a tree identical to the species tree is returned (it is relabele however).
#'
#' Transfers are implemented as a birth-death process.
#' One descendant lineage retains its species identity the other gains a new identity.
#' At present, two types of transfers are implemented: "random" an "cladewise".
#' The random transfer mode transfers one randomly chooses a contemporaneous lineage.
#' Cladewise transfers choose lineages based on relatedness with more closely related lineages being more likely.
#' @references
#' Rasmussen MD, Kellis M. Unified modeling of gene duplication, loss, and
#'     coalescence using a locus tree. Genome Res. 2012;22(4):755–765.
#'     doi:10.1101/gr.123901.111
#' @examples
#' # first simulate a species tree
#' mu <- 0.5 # death rate
#' lambda <- 2.0 # birth rate
#' numb_replicates <- 10
#' numb_extant_tips <- 4
#' # simulate trees under the GSA so first simulates a tree with
#' # numb_extant_tips * 100 tips counting each time we have a tree with 10 tips
#' # then randomly picks one of those trees
#'
#' sp_tree <- sim_sptree_bdp(sbr = lambda,
#'                 sdr = mu,
#'                 numbsim = numb_replicates,
#'                 n_tips = numb_extant_tips)
#'
#' gene_br <- 1.0
#' gene_dr <- 0.2
#' transfer_rate <- 0.2
#' sim_locustree_bdp(species_tree = sp_tree[[1]],
#'                   gbr = gene_br,
#'                   gdr = gene_dr,
#'                   lgtr = transfer_rate,
#'                   num_loci = 10)
sim_locustree_bdp <- function(species_tree, gbr, gdr, lgtr, num_loci, transfer_type = "random") {
    .Call(`_treeducken_sim_locustree_bdp`, species_tree, gbr, gdr, lgtr, num_loci, transfer_type)
}

#' Simulates a cophylogenetic system using a paired birth-death process
#'
#' @details Simulates a cophylogenetic system using birth-death processes. The
#'     host tree is simulated following a constant rate birth-death process
#'     with an additional parameter - the cospeciation rate. This rate works as
#'     the speciation rate with the additional effect that if cospeciation
#'     occurs the symbiont tree also speciates. The symbiont tree is related to
#'     the host tree via an association matrix that describes which lineages
#'     are associated with which. The symbiont tree has an independent
#'     birth-death process with the addition of a host shift speciation rate
#'     that allows for the addition of more associated hosts upon symbiont
#'     speciation.
#' @param hbr host tree birth rate
#' @param hdr host tree death rate
#' @param sbr symbiont tree birth rate
#' @param sdr symbiont tree death rate
#' @param host_exp_rate host shift speciation rate
#' @param cosp_rate cospeciation rate
#' @param time_to_sim time units to simulate until
#' @param numbsim number of replicates
#' @return A list containing the `host_tree`, the `symbiont_tree`, the
#'     association matrix at present, and the history of events that have
#'     occurred.
#' @examples
#'
#' host_mu <- 0.5 # death rate
#' host_lambda <- 2.0 # birth rate
#' numb_replicates <- 10
#' time <- 1.0
#' symb_mu <- 0.2
#' symb_lambda <- 0.4
#' host_shift_rate <- 0.1
#' cosp_rate <- 2.0
#'
#' cophylo_pair <- sim_cophylo_bdp(hbr = host_lambda,
#'                            hdr = host_mu,
#'                            cosp_rate = cosp_rate,
#'                            host_exp_rate = host_shift_rate,
#'                            sdr = symb_mu,
#'                            sbr = symb_lambda,
#'                            numbsim = numb_replicates,
#'                            time_to_sim = time)
#'
sim_cophylo_bdp <- function(hbr, hdr, sbr, sdr, host_exp_rate, cosp_rate, time_to_sim, numbsim) {
    .Call(`_treeducken_sim_cophylo_bdp`, hbr, hdr, sbr, sdr, host_exp_rate, cosp_rate, time_to_sim, numbsim)
}

#' Simulate locus tree within species tree and gene trees within locus tree
#'
#' @description First simulates a locus tree within the confines of the input species tree using a constant-rate birth-death process
#' based on values of `gbr`, `gdr` and `lgtr`. Then simulates gene trees within that locus tree using the multispecies coalescent process.
#' This is not sensible in most cases as there should be coalescent bounds at duplications and this function may be removed in the future
#' @param species_tree input species tree of class "phylo"
#' @param gbr gene birth rate
#' @param gdr gene death rate
#' @param lgtr lateral gene transfer rate'
#' @param theta the population genetic parameter
#' @param num_sampled_individuals number of individuals sampled within each locus lineage
#' @param num_loci number of loci to simulate
#' @param num_genes_per_locus number of genes to simulate within each locus
#'
#' @return A list of lists of length 2. The first element of each list of length 2 is `locus.tree` the locus tree and the second element is a list of the gene trees simulated within that locus tree. All trees are of class "phylo".
#'
#' @seealso sim_locustree_bdp
#'
#' @examples
#' # first simulate a species tree
#' mu <- 0.5
#' lambda <- 1.0
#' nt <- 6
#' tr <- sim_sptree_bdp(sbr = lambda, sdr = mu, numbsim = 1, n_tips = nt)
#' # for a locus tree with 100 genes sampled per locus tree
#' loctr_gentr <- sim_locustree_genetree_msc(tr[[1]],
#'                                            gbr = 0.1,
#'                                            gdr = 0.0,
#'                                            lgtr = 0.0,
#'                                            theta = 1,
#'                                            num_sampled_individuals = 1,
#'                                            num_loci = 4,
#'                                            num_genes_per_locus = 100)
#'
#' @references
#' Mallo D, de Oliveira Martins L, Posada D (2015) SimPhy: Phylogenomic Simulation of Gene, Locus and Species Trees. Syst. Biol. doi: http://dx.doi.org/10.1093/sysbio/syv082
sim_locustree_genetree_msc <- function(species_tree, gbr, gdr, lgtr, num_loci, num_sampled_individuals, theta, num_genes_per_locus) {
    .Call(`_treeducken_sim_locustree_genetree_msc`, species_tree, gbr, gdr, lgtr, num_loci, num_sampled_individuals, theta, num_genes_per_locus)
}

#' Simulate multispecies coalescent on a species tree
#'
#' @description Simulates the multispecies coalescent on a species tree.
#' @param species_tree input species tree of class "phylo"
#' @param ne Effective population size
#' @param mutation_rate The rate of mutations per generation
#' @param generation_time Number of generations per species tree length
#' @param num_sampled_individuals number of individuals sampled within each lineage
#' @param num_genes number of genes to simulate within each locus
#' @param mutation_rate The rate of mutation per generation
#'
#'
#' @return A list of coalescent trees
#' @seealso sim_locustree_bdp, sim_sptree_bdp, sim_sptree_bdp_time
#'
#' @examples
#' # first simulate a species tree
#' mu <- 0.5
#' lambda <- 1.0
#' nt <- 6
#' tr <- sim_sptree_bdp(sbr = lambda, sdr = mu, numbsim = 1, n_tips = nt)
#' # for a locus tree with 100 genes sampled per locus tree
#' loctr_gentr <- sim_multispecies_coal(tr[[1]],
#'                                     ne = 1,
#'                                     num_sampled_individuals = 1,
#'                                     num_genes = 100)
#'
#' @references
#' Mallo D, de Oliveira Martins L, Posada D (2015) SimPhy: Phylogenomic Simulation of Gene, Locus and Species Trees. Syst. Biol. doi: http://dx.doi.org/10.1093/sysbio/syv082
sim_multispecies_coal <- function(species_tree, ne, num_sampled_individuals, num_genes, mutation_rate = 1.0, generation_time = 1.0) {
    .Call(`_treeducken_sim_multispecies_coal`, species_tree, ne, num_sampled_individuals, num_genes, mutation_rate, generation_time)
}

